# Generated by Django 5.2.1 on 2025-05-22 01:51

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=uploads.models.get_project_upload_path),
        ),
    ]
