# Generated by Django 5.2.1 on 2025-05-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='title',
        ),
    ]
