# Generated by Django 5.2.1 on 2025-05-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_invitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-uploaded_at'], 'permissions': [('view_own_files', 'Can view only their own files')]},
        ),
    ]
